spring:
  mail:
    host: smtp.163.com #SMTP服务器地址
    username: socks #登陆账号
    password: 123456 #登陆密码（或授权码）
    properties:
      from:  socks@163.com #邮件发信人（即真实邮箱）
  thymeleaf:
    cache: false
    prefix: classpath:/views/
  servlet:
    multipart:
      max-file-size: 10MB #限制单个文件大小
      max-request-size: 50MB #限制请求总量